### ISSUE TITLE
I feel that the judgement at line 129 in myTools.h can't achieve its aim

### ISSUE THREAD

**Issue by 2897035088** [zikai1/CircleDetection#1]
its source code : if (SignS1 * SignE1 >= 0 || SignS2 * SignE2 >= 0).

**Comment by 2897035088** [comment]
I feel that it may be this: if ((SignM2 * SignS1) <= 0 &&  (SignM2 * SignE1 <= 0) && (SignM1 * SignS2 <=0) && (SignM1 * SignE2 <= 0))

**Comment by zikai1** [comment]
Hi,
Thanks for pointing out this！In the implementation, I accelerated the relative position judgement using (SignS1 * SignE1 >= 0 || SignS2 * SignE2 >= 0) and put more restrict judgements based on the constraint 2, but in fact the more solid judgement is what you have pointed. Thanks again!

**Comment by zikai1** [comment]
> I feel that it may be this: if ((SignM2 * SignS1) <= 0 && (SignM2 * SignE1 <= 0) && (SignM1 * SignS2 <=0) && (SignM1 * SignE2 <= 0))

Hi,
Thanks for pointing out this！In the implementation, I accelerated the relative position judgement using (SignS1 * SignE1 >= 0 || SignS2 * SignE2 >= 0) and put more restrict judgements based on the constraint 2, but in fact the more solid judgement is what you have pointed. Thanks again!

**Comment by zikai1** [comment]
> I feel that it may be this: if ((SignM2 * SignS1) <= 0 && (SignM2 * SignE1 <= 0) && (SignM1 * SignS2 <=0) && (SignM1 * SignE2 <= 0))

Hi,
Thanks for pointing out this! During the implementation, I accelerated the relative position judgement by relaxing `((SignM2 * SignS1) <= 0 && (SignM2 * SignE1 <= 0) && (SignM1 * SignS2 <=0) && (SignM1 * SignE2 <= 0))` to `(SignS1 * SignE1 >= 0 || SignS2 * SignE2 >= 0)`, and gave more restrict judgements based on the Constraint 2. But the more solid position constraint is what you have pointed. Thanks again!

**Comment by 2897035088** [comment]
oh,  I see.  Thanks for your answer!
