### ISSUE TITLE
The test code gets stuck

### ISSUE THREAD

**Issue by yashbohra07** [zikai1/CircleDetection#2]
I am running test.cpp, it gets stuck when running on dataset_MY, dataset_PCB, dataset_GH but runs properly on dataset_Mini. While debugging i figured out that it gets stuck at coCircleGroupArcs() . Is it a known issue?

**Comment by zikai1** [comment]
> I am running test.cpp, it gets stuck when running on dataset_MY, dataset_PCB, dataset_GH but runs properly on dataset_Mini. While debugging i figured out that it gets stuck at coCircleGroupArcs() . Is it a known issue?

Hello, thanks for your interest. I will check into what happened right away.

Best, 
MY

**Comment by zikai1** [comment]
> I am running test.cpp, it gets stuck when running on dataset_MY, dataset_PCB, dataset_GH but runs properly on dataset_Mini. While debugging i figured out that it gets stuck at coCircleGroupArcs() . Is it a known issue?

Hi, we have tested the code on the other three datasets and there is no bug reported. Our test environment is 
`vs2022，opencv4.7 with 13th Gen Intel(R) Core(TM) i9-13900HX   2.20 GHz`

Could you please post the bug here for our in-depth analysis. Thx.

**Comment by yashbohra07** [comment]
Hi, thanks for your response.

My test environment is `opencv 4.8 with 12th Gen Intel (R) Core i5-12400Fx12 4.40 GHz` , i use makefile for building, not using visual studio.

While debugging a bit deeper, I found that the code gets stuck inside pinv_eigen_based(). I guess the svd_holder() is not functioning as expected. 

Please check.

**Comment by zikai1** [comment]
> Hi, thanks for your response.
> 
> My test environment is `opencv 4.8 with 12th Gen Intel (R) Core i5-12400Fx12 4.40 GHz` , i use makefile for building, not using visual studio.
> 
> While debugging a bit deeper, I found that the code gets stuck inside pinv_eigen_based(). I guess the svd_holder() is not functioning as expected.
> 
> Please check.

Hi, 

My test environment is Visual Studio. Maybe it is the issue of the makefile? 

Could you try VS for testing?

**Comment by yashbohra07** [comment]
I will check on VS but I don't think it is a makefile issue because it stucks on after running on some of the images and not at the first image itself. 
The reason behind compiling using makefile is that i will be running it on ubuntu.

**Comment by zikai1** [comment]
Hello, I temporarily close this issue. Please feel free to reopen it if there are still any concerns or unresolved matters.
